### ISSUE TITLE
Error when using TLS

### ISSUE THREAD

**Issue by Dffy244** [peterprib/node-red-contrib-kafka-manager#14]
Hi Peter,

Kafka Manager works fine for my until I start to try using TLS.
I'm strugglign with it for quite a while already I didn't find a resolution. When using TLS I always run into the error message like below:

> 1 Mar 17:29:35 - [error] [Kafka Broker:88d4e3c4.25f6d8] TypeError: Cannot set property 'key' of undefined

The same TLS configuration used works fine when e.g. using MQTT. 
Version of node-red-contrib-kafka-manager is 0.2.11

Did you run into this before?

Kind regards

Michael

**Comment by peterprib** [comment]
No.  Will look at tonight

**Comment by peterprib** [comment]
Had a look and can't see where property "key" is used around tls logic or in Kafka broker.  Could you send more details from the log.  In particular stack trace if exists. Log messages before and after this message.   May be an issue in a module it calls expecting this property.

The only issue I can see is I have nested the tls config node in a config node.  This has been an issue in the past. May need to pull this up a level, that is TLS information set at broker node

**Comment by Dffy244** [comment]
I did replicate the issue with a very basic flow. All it contains is a Kafka consumer writing to the debug node. The trace shows starting up node-red and the flow with TLS enabled (and shows the issue). After 15 secs or so I disabled TLS and deployed the flow again (the issue goes away and the consumer is trying to connect. Connection fails as it is not a real Kafka node it is connecting to though.)

PS: There is no network activity at all (checked with Wireshark) with TLS enabled and the error showing up

[logfile.txt](https://github.com/peterprib/node-red-contrib-kafka-manager/files/4294284/logfile.txt)

I hope the trace is helpful. Please let me know if I should look for other logs....

**Comment by peterprib** [comment]
Is nesting.  Will have to investigate a way around or drag TLS node logic into broker module.

**Comment by peterprib** [comment]
Think I have fixed.  At least fixed the issue it was having,  Have enabled self serve on certificate.  Have published: 2.12

**Comment by Dffy244** [comment]
Thank you

I need to do a little more testing

I still get an error message though when starting it with TLS
> "get node tls 5e4581c5.4ef798 failed, error:TypeError: options.sslOptions.keys is not a function"

Also it seems as if enabling TLS doesn't persist in that node when restarting node-red. But I need to verify that. Please see logfile attached. 
[logfile2.txt](https://github.com/peterprib/node-red-contrib-kafka-manager/files/4311022/logfile2.txt)

**Comment by peterprib** [comment]
The message is not causing any issue but will fix when I get a chance.. Just bug with leaving some tracing information  Have noticed it tracing cert information in log which I will removed as well.  But this should proved it persists TLS information.
